-- UNION operator


SELECT *
FROM SALES_HISTORY;

SELECT *
FROM SALES;

--First result set
SELECT 
SALES_DATE, PRODUCT_ID, CUSTOMER_ID
FROM SALES; 


--Second result set
SELECT 
SALES_DATE, PRODUCT_ID, CUSTOMER_ID
FROM SALES_HISTORY; 


--Combining 2 tables
SELECT 
SALES_DATE, PRODUCT_ID, CUSTOMER_ID
FROM SALES
UNION
SELECT 
SALES_DATE, PRODUCT_ID, CUSTOMER_ID
FROM SALES_HISTORY; 