-- GROUP BY WITH MULTIPLE COLUMNS
SELECT * 
FROM SALES;

SELECT 
SALES_DATE, PRODUCT_ID, CUSTOMER_ID
FROM SALES
WHERE SALES_DATE BETWEEN '01-JAN-15' AND '31-JAN-15';
GROUP BY SALES_DATE, PRODUCT_ID;

SELECT 
SALES_DATE, PRODUCT_ID, SUM(TOTAL_AMOUNT) "TOTAL_SALES" 
FROM SALES
WHERE SALES_DATE BETWEEN '01-JAN-15' AND '31-JAN-15'
GROUP BY SALES_DATE, PRODUCT_ID
ORDER BY SALES_DATE;


SELECT 
SALES_DATE, PRODUCT_ID,CUSTOMER_ID,SUM(TOTAL_AMOUNT) "TOTAL_SALES" 
FROM SALES
WHERE SALES_DATE BETWEEN '01-JAN-15' AND '31-JAN-15'
GROUP BY SALES_DATE, PRODUCT_ID, CUSTOMER_ID
ORDER BY SALES_DATE;