--Filtering data accroding to aggregate function

SELECT * 
FROM SALES;

SELECT 
SALES_DATE, PRODUCT_ID, SUM(TOTAL_AMOUNT) "TOTAL AMONUT"
FROM SALES
WHERE SALES_DATE BETWEEN '01-JAN-15' AND '31-JAN-15'
GROUP BY SALES_DATE, PRODUCT_ID
HAVING SUM(TOTAL_AMOUNT)> 100
ORDER BY SALES_DATE;